# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: ContainerBuild@0
      inputs:
        dockerRegistryServiceConnection: 'dockerHub'
        repository: 'postgres'
        Dockerfile: 'Dockerfile'
        tags: '9.6.24'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerHub'
        repository: 'smallac/azure_docker_ckan_test_001'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'